### ISSUE TITLE
Processing RTPLAN modality

### ISSUE THREAD

**Issue by SWKoreaBME** [bhklab/med-imagetools#79]
Hi, I'm trying to process using autopipeline for two modalities: CT and RTPLAN. 
But when I tried putting RTPLAN, it breaks with an error.

```
Forming the graph based on the given modalities: CT,RTPLAN
Traceback (most recent call last):
  File "/miniconda3/envs/torch38/bin/autopipeline", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/torch38/lib/python3.8/site-packages/imgtools/autopipeline.py", line 740, in main
    pipeline = AutoPipeline(**args_dict)
  File "/miniconda3/envs/torch38/lib/python3.8/site-packages/imgtools/autopipeline.py", line 322, in __init__
    self.input = ImageAutoInput(input_directory, modalities, n_jobs, visualize, update)
  File "/miniconda3/envs/torch38/lib/python3.8/site-packages/imgtools/ops/ops.py", line 175, in __init__
    self.df_combined = graph.parser(self.modalities)
  File "/miniconda3/envs/torch38/lib/python3.8/site-packages/imgtools/modules/datagraph.py", line 292, in parser
    raise ValueError("Invalid Query. Select valid pairs.")
ValueError: Invalid Query. Select valid pairs.
```

It seems that indexing does work, the file says there's RTPLAN dicom files in the folder but I don't know why it raises valuerror.

Any thoughts on this error? 

Best,
Sangwook

**Comment by skim2257** [comment]
In our testing, RTPLAN files didn't have any inherent image matrices, thus it is an unsupported DICOM modality. 
Do you have any samples with RTPLAN matrix data? As far as we know, only RTDOSE have the matrix-level data for radiotherapy.
